
categories = dict()

categories["moods"] = [
    "Atmospheric",
    "Biting",
    "Bittersweet",
    "Bleak",
    "Captivating",
    "Clever",
    "Contemplative",
    "Cynical",
    "Disturbing",
    "Emotional",
    "Exciting",
    "Feel Good",
    "Gloomy",
    "Humorous",
    "Mind Bending",
    "Offbeat",
    "Rough",
    "Scary",
    "Sentimental",
    "Sexual",
    "Sexy",
    "Sincere",
    "Stylized",
    "Suspenseful",
    "Tense",
    "Thought Provoking",
    "Touching",
    "Uplifting",
    "Witt",
]

categories["plot"] = [
    "Against the Odds",
    "Ambition",
    "Americana",
    "Animal life",
    "Artists and Showbiz",
    "Athlete's Life",
    "Chaos",
    "Chases and Races",
    "Cons and Scams",
    "Couples",
    "Criminal Heroes",
    "Deadly Creature",
    "Disaster",
    "Dysfunctional Family",
    "Fall in Love",
    "Family Relations",
    "Feminism",
    "Fighting the System",
    "Fish Out of Water",
    "Friendship",
    "Gender",
    "Heroes",
    "Human Spirit",
    "Imaginary",
    "Infidelity",
    "Introspection",
    "Law Enforcement",
    "Legal",
    "Life is a Bitch",
    "Media",
    "Mind Game",
    "Murder",
    "Nothing Goes Right",
    "Obsession",
    "Psychological",
    "Rescue",
    "Save the World",
    "Serial Killer",
    "Social Relations",
    "Society",
    "Space and Aliens",
    "Starting Over",
    "State Affairs",
    "Supernatural",
    "Teachers and Students",
    "Terrorism",
    "Uncover Truth",
    "Undercover",
    "Uninhibited Rivalry",
    "Vampire",
    "Vengeance",
    "Violence Spree",
    "Workplace",
    "Youth",
    "Zombi",
]

categories["genres"] = [
    "Action",
    "Adventure",
    "Animation",
    "Anime",
    "Arts and Culture",
    "Biography",
    "Bollywood",
    "Business and Finance",
    "Comedy",
    "Crime",
    "Culinary",
    "Documentary",
    "Drama",
    "Educational",
    "Erotic",
    "Family",
    "Fantasy",
    "Foreign",
    "Game Show",
    "Health and Fitness",
    "Historical",
    "Home and Garden",
    "Horror",
    "How To",
    "Independent",
    "Lifestyle",
    "Martial Arts",
    "Medical",
    "Motor",
    "Music",
    "Music Concert",
    "Musical",
    "Mystery",
    "Nature",
    "News",
    "Period",
    "Reality",
    "Religious",
    "Romance",
    "Sci-Fi",
    "Science and Technology",
    "Shopping",
    "Sitcom",
    "Soap Opera",
    "Sport",
    "Stand Up and Sketches",
    "Talk Show",
    "Thriller",
    "Travel and Leisure",
    "Variety and Entertainment",
    "War",
    "Web Series",
    "Wester",
]

categories["time-period"] = [
    "15th Century",
    "16th Century",
    "17th Century",
    "18th Century",
    "1900s",
    "1910s",
    "19th Century",
    "20s",
    "20th Century",
    "21st Century",
    "30s",
    "40s",
    "50s",
    "60s",
    "70s",
    "80s",
    "90s",
    "American Civil War",
    "Ancient History",
    "Contemporary",
    "D Day",
    "Future",
    "Gulf War",
    "Middle Ages",
    "Old West",
    "Prehistory",
    "Victorian",
    "Vietnam War",
    "World War 1",
    "World War ",
]

categories["place"] = [
    "Africa",
    "Airplane",
    "Airport",
    "Asia",
    "Australia",
    "Bar",
    "Battle Zone",
    "Casino",
    "Chicago",
    "China",
    "College",
    "Countryside",
    "Courtroom",
    "Cross Country",
    "Desert",
    "Distant Planet",
    "England",
    "Estate",
    "Europe",
    "Farm",
    "France",
    "Germany",
    "Haunted House",
    "High School",
    "Hollywood",
    "Hotel",
    "In the Woods",
    "India",
    "Indoors",
    "Island",
    "Italy",
    "Japan",
    "Jungle",
    "Las Vegas",
    "Latin America",
    "London",
    "Los Angeles",
    "Mars",
    "Middle East",
    "Moon",
    "Mountains",
    "New York",
    "Ocean or Sea",
    "Office",
    "Outer Space",
    "Palaces Castles and Temples",
    "Paris",
    "Prison",
    "Resort",
    "Restaurant",
    "Roman Empire",
    "Rome",
    "Royal Court",
    "Russia",
    "San Francisco",
    "Ship",
    "Small Town",
    "Spacecraft",
    "Spain",
    "Suburbs",
    "USA",
    "Underwater",
    "University",
    "Urban",
    "Urban Ghetto",
    "Village",
    "Washington DC",
    "White House",
    "Wilderness",
    "World Spannin",
]

categories["audience"] = [
    "Boys' Night",
    "Date Night",
    "Family Outing",
    "Girls' Nigh",
    "Kids",
    "Teen",
]

categories["praise"] = [
    "Award Winner",
    "Berlin Festival Winner",
    "Blockbuster",
    "Cannes Festival Winner",
    "Classic",
    "Controversial",
    "Critically Acclaimed",
    "Cult",
    "Emmy Winner",
    "Essential",
    "Golden Globe Winner",
    "Groundbreaking",
    "Highly Acclaimed Short",
    "Hit TV Series",
    "Masterpiece",
    "Modern Classic",
    "Original",
    "Oscar Winner",
    "Prestigious Awards",
    "Sundance Festival Winner",
    "Venice Festival Winne",
]

categories["humor"] = [
    "Comedy of Errors",
    "Dark Humor",
    "Dry Humor",
    "Farce",
    "Grossout Humor",
    "Irreverent Humor",
    "Satire",
    "Screwball",
    "Silly Humor",
    "Slapstick",
    "Verbal Bypla",
]

categories["style"] = [
    "All Star Cast",
    "Archive Footage",
    "Campy",
    "Co-hosting",
    "Continuous",
    "Debate",
    "Ensemble Cast",
    "Epic",
    "Episodic",
    "Fairytale",
    "Film in Film",
    "Gory",
    "Gothic",
    "Hosted",
    "Interactive",
    "Interviews",
    "Live",
    "Magazine",
    "Multiple Stories",
    "Nonlinear",
    "On the Road",
    "Panel",
    "Reenactment",
    "Saga",
    "Stand Alone",
    "Stories(articles)",
    "Strong Female Presence",
    "Surreal",
    "Talky",
    "Topical",
    "Twists and Turns",
    "Unscripted or Improvised",
    "Voice Ove",
]

categories["basedon"] = [
    "Based on Article",
    "Based on Book",
    "Based on Comics",
    "Based on Film",
    "Based on Play",
    "Based on Short Film",
    "Based on Short Story",
    "Based on TV Series",
    "Based on True Story",
    "Based on Video Game",
    "Based on Web",
    "Remak",
]

