# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-11 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movietags',
            name='category',
        ),
        migrations.AddField(
            model_name='movietags',
            name='type',
            field=models.CharField(default='t', max_length=1, verbose_name='Tag Type'),
        ),
    ]
