# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-17 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20161011_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='movietags',
            name='n',
            field=models.IntegerField(default=0, verbose_name='Count'),
        ),
    ]
