# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-17 17:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movietags_n'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimilarMovieRel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(verbose_name='Score')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Movie')),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='similar',
            field=models.ManyToManyField(through='movies.SimilarMovieRel', to='movies.Movie'),
        ),
    ]
