# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-17 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20161017_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='similarmovierel',
            name='basedon',
            field=models.CharField(default='', max_length=5, verbose_name='Based On'),
        ),
    ]
