# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-17 19:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_similarmovierel_basedon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='similarmovierel',
            old_name='movie',
            new_name='linkfrom',
        ),
        migrations.RenameField(
            model_name='similarmovierel',
            old_name='similar',
            new_name='linkto',
        ),
    ]
