# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-18 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_auto_20161017_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='similarmovierel',
            name='votes',
            field=models.IntegerField(default=0, verbose_name='Votes'),
        ),
    ]
