# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-18 19:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0009_similarmovierel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='similarmovierel',
            name='op_message',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='similarmovierel',
            name='op_rating',
            field=models.SmallIntegerField(default=99, verbose_name='Rate Similar'),
        ),
        migrations.AddField(
            model_name='similarmovierel',
            name='reason',
            field=models.CharField(default='None given', max_length=200, verbose_name='Reason'),
        ),
        migrations.AddField(
            model_name='similarmovierel',
            name='votefrom',
            field=models.ManyToManyField(related_name='simvotefrom', to=settings.AUTH_USER_MODEL),
        ),
    ]
