# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-20 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_auto_20161018_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='postersaved',
            field=models.BooleanField(default=False),
        ),
    ]
